const fs = require('fs');

const fullSchedule = [
  ['Chevrolet','CR7 Motorsports','97','Jason Kitzmiller','Frank Kimmel'],
  ['Chevrolet','Maples Motorsports','99','Michael Maples','Chris Vanscoy'],
  ['Chevrolet','Pinnacle Racing Group','28','Jack Wood','Steven Dawson'],
  ['Chevrolet','Pinnacle Racing Group','28','Carson Brown','Steven Dawson'],
  ['Chevrolet','Pinnacle Racing Group','28','Connor Mosack','Steven Dawson'],
  ['Chevrolet','Pinnacle Racing Group','77','Taylor Reimer','Kevin Reed Jr.'],
  ['Chevrolet','Pinnacle Racing Group','77','Tristan McKee','Kevin Reed Jr.'],
  ['Chevrolet','Pinnacle Racing Group','77','Lanie Buice','Kevin Reed Jr.'],
  ['Chevrolet','Rise Racing with Earnhardt-Shearer Racing','89','Bobby Dale Earnhardt','Matthew Wright'],
  ['Ford','Clubb Racing Inc.','03','Alex Clubb','Brian Clubb'],
  ['Ford','Clubb Racing Inc.','86','Logan Misuraca','Ryan Bell'],
  ['Ford','Clubb Racing Inc.','86','Jeff Maconi','TBA'],
  ['Ford','Clubb Racing Inc.','86','Chris Golden','TBA'],
  ['Ford','Clubb Racing Inc.','86','TBA','TBA'],
  ['Ford','SPS Racing','24','Daniel Dye','Blake Bainbridge'],
  ['Ford','SPS Racing','24','TBA','TBA'],
  ['Toyota','Fast Track Racing','12','Takuma Koga','Andrew Kierman'],
  ['Toyota','Joe Gibbs Racing','18','Gio Ruggiero','Matt Ross'],
  ['Toyota','Joe Gibbs Racing','18','Max Reaves','Matt Ross'],
  ['Toyota','Joe Gibbs Racing','18','TBA','TBA'],
  ['Toyota','Nitro Motorsports','15','Jake Finch','Danny Johnson'],
  ['Toyota','Nitro Motorsports','15','Mia Lovell','TBA'],
  ['Toyota','Nitro Motorsports','15','Leland Honeyman','TBA'],
  ['Toyota','Nitro Motorsports','15','TBA','TBA'],
  ['Toyota','Nitro Motorsports','20','Jake Bollman (R)','Doug George'],
  ['Toyota','Nitro Motorsports','25','Gus Dean','Shane Wilson'],
  ['Toyota','Nitro Motorsports','25','Julian DaCosta','TBA'],
  ['Toyota','Nitro Motorsports','25','Gavan Boschele','TBA'],
  ['Toyota','Nitro Motorsports','25','TBA','TBA'],
  ['Toyota','Nitro Motorsports','55','Isabella Robusto','Glenn Parker'],
  ['Toyota','Nitro Motorsports','70','Thomas Annunziata','Shannon Rursch'],
  ['Ford','Fast Track Racing','9','Presley Sorah','Joseth Carabantes'],
  ['Ford','Fast Track Racing','9','TBA','TBA'],
  ['Chevrolet','Fast Track Racing','10','Ed Pompa','Mike Sroufe'],
  ['Chevrolet','Fast Track Racing','10','TBA','TBA'],
  ['Toyota','Fast Track Racing','11','Bryce Haugeberg','Dick Doheny'],
  ['Toyota','Fast Track Racing','11','TBA','TBA'],
  ['Ford','Brad Smith Motorsports','48','Brad Smith','Terry Strange'],
  ['Ford','Brad Smith Motorsports','48','TBA','TBA'],
  ['Ford','Maples Motorsports','1','Tony Cosentino','Jay Shaffer'],
  ['Ford','Maples Motorsports','1','TBA','TBA'],
  ['Ford','Maples Motorsports','91','Ryan Vargas','Kyle Totman'],
];

const limitedSchedule = [
  ['Chevrolet','ACR Motorsports','79','Isaac Kitzmiller','TBA'],
  ['Chevrolet','Andrew Patterson Racing','40','Andrew Patterson','Patrick Torbett'],
  ['Chevrolet','Bill McAnally Racing','16','Hailie Deegan','TBA'],
  ['Chevrolet','Bill McAnally Racing','19','Mason Massey','TBA'],
  ['Chevrolet','Brother-In-Law Racing','57','Hunter Deshautelle','Todd Cooper'],
  ['Chevrolet','Brother-In-Law Racing','75','Bryan Dauzat','Bob Rahilly'],
  ['Chevrolet','Cook Racing Technologies','17','Mini Tyrrell','Sean Samuels'],
  ['Chevrolet','Costner Motorsports','93','Caleb Costner','Unknown'],
  ['Chevrolet','Empire Racing','8','Sean Corr','Dan Lorz'],
  ['Chevrolet','Kimmel Racing','69','Nolan Wilson','Bill Kimmel'],
  ['Chevrolet','Maples Motorsports','19','Greg Van Alst','Jim Long'],
  ['Chevrolet','Moyer–Petroniro Racing','88','A. J. Moyer','Kevin Ingram'],
  ['Chevrolet','Mullins Racing','34','Bryce Applegate','Tony Furr'],
  ['Chevrolet','Steve Lewis Racing','62','Steve Lewis Jr.','Steve Lewis Sr.'],
  ['Chevrolet','Wayne Peterson Motorsports','06','Con Nicolopoulos','Michael Peterson'],
  ['Chevrolet','Weslowski Racing','32','Charles Weslowski Jr.','Tim Silva'],
  ['Chevrolet','White Motorsports','22','Nick White','Unknown'],
  ['Ford','City Garage Motorsports','5','Quinn Davis','TBA'],
  ['Ford','City Garage Motorsports','85','Becca Monopoli','TBA'],
  ['Ford','Direct Driver Development','50','Ryan Pawloski','TBA'],
  ['Ford','Direct Driver Development','60','TBA','TBA'],
  ['Ford','High Point Racing','50','Trevor Huddleston','TBA'],
  ['Ford',"Jan's Towing Racing with Kennealy Keller Motorsports",'1','Robbie Kennealy','TBA'],
  ['Ford',"Jan's Towing Racing with Kennealy Keller Motorsports",'41','Tim Monroe','TBA'],
  ['Ford',"Jan's Towing Racing with Kennealy Keller Motorsports",'71','Cole Denton','TBA'],
  ['Ford','Kimmel Racing','68','Alli Owens','Will Kimmel'],
  ['Ford','KLAS Motorsports','07','Glen Reen','Justin Link'],
  ['Ford','MBM Motorsports','66','Derek White','Jeremy Petty'],
  ['Ford','Mullins Racing','3','Willie Mullins','Alex Quarterley'],
  ['Ford','Rette Jones Racing','30','Garrett Mitchell','Mark Rette'],
  ['Ford','Rette Jones Racing','30','George Siciliano','TBA'],
  ['Ford','Rette Jones Racing','76','Kole Raz','Greg Zipadelli'],
  ['Ford','Ryan Huff Motorsports','36','Ryan Huff','James Huff'],
  ['Toyota','CCM Racing','7','Eric Caudell','Andy Jirik'],
  ['Toyota','Jerry Pitts Racing','5','Eric Johnson Jr.','TBA'],
  ['Toyota','Jerry Pitts Racing','7','Gavin Ray','TBA'],
  ['Toyota','Martin Racing','52','Robert Martin','Jeff Spraker'],
  ['Toyota','Nitro Motorsports','90','Wesley Slimp','Jeff McClure'],
  ['Toyota','Nitro Motorsports','90','TBA','TBA'],
  ['Toyota','TBA','TBA','Jake Finch','TBA'],
  ['Toyota','TBA','TBA','Gus Dean','TBA'],
  ['Toyota','TBA','TBA','Sam Corry','TBA'],
  ['Toyota','TBA','TBA','Jade Avedisian','TBA'],
  ['Toyota','Shearer Speed Racing','98','Dale Shearer','Vincenzo Valentin'],
  ['Toyota','Tim Richmond Racing','27','Tim Richmond','Adam Murphy'],
  ['Toyota','Vanco Racing','26','Ron Vandermeir Jr.','Unknown'],
  ['Chevrolet','KLAS Motorsports','71','Andy Jankowiak','Mike Dayton'],
  ['TBA','Fast Track Racing','TBA','Craig Pellegrini Jr.','TBA'],
  ['TBA','KLAS Motorsports','73','TBA','TBA'],
  ['TBA','TBA','0','Laci Ferno','TBA'],
];

function rowToTeam(r, fullTime) {
  return {
    manufacturer: r[0],
    team: r[1],
    number: r[2],
    driver: r[3],
    crew_chief: r[4] || '',
    full_time: fullTime,
  };
}

const teams = [
  ...fullSchedule.map(r => rowToTeam(r, true)),
  ...limitedSchedule.map(r => rowToTeam(r, false)),
];

const out = { teams };
fs.writeFileSync('data/teams/ARCA.json', JSON.stringify(out, null, 2), 'utf8');
console.log('Wrote data/teams/ARCA.json:', teams.length, 'teams (Full:', fullSchedule.length, ', Limited:', limitedSchedule.length, ')');
