const fs = require('fs');

const entryList = [
  ['1', 'Tony Cosentino', 'Maples Motorsports', 'Ford', 'Jay Shaffer'],
  ['03', 'Alex Clubb', 'Clubb Racing Inc.', 'Ford', 'Brian Clubb'],
  ['3', 'Willie Mullins', 'Mullins Racing', 'Ford', '—'],
  ['06', 'Con Nicolopoulos', 'Wayne Peterson Motorsports', 'Chevrolet', 'Michael Peterson'],
  ['07', 'Glen Reen', 'KLAS Motorsports', 'Ford', 'Andy Jirik'],
  ['7', 'Eric Caudell', 'CCM Racing', 'Toyota', 'Justin Link'],
  ['8', 'Sean Corr', 'Empire Racing', 'Chevrolet', 'Dan Lorz'],
  ['9', 'Presley Sorah', 'Fast Track Racing', 'Ford', 'Joseth Carabantes'],
  ['10', 'Ed Pompa', 'Fast Track Racing', 'Chevrolet', 'Mike Sroufe'],
  ['11', 'Bryce Haugeberg', 'Fast Track Racing', 'Toyota', 'Dick Doheny'],
  ['12', 'Takuma Koga', 'Fast Track Racing', 'Toyota', 'Andrew Kiernan'],
  ['15', 'Jake Finch', 'Nitro Motorsports', 'Toyota', 'Danny Johnson'],
  ['17', 'Mini Tyrrell', 'Cook Racing Technologies', 'Chevrolet', 'Sean Samuels'],
  ['18', 'Gio Ruggiero', 'Joe Gibbs Racing', 'Toyota', 'Matt Ross'],
  ['19', 'Greg Van Alst', 'Maples Motorsports', 'Chevrolet', 'Jim Long'],
  ['20', 'Jake Bollman (R)', 'Nitro Motorsports', 'Toyota', 'Doug George'],
  ['22', 'Nick White', 'White Motorsports', 'Chevrolet', '—'],
  ['24', 'Daniel Dye', 'SPS Racing', 'Ford', 'Blake Bainbridge'],
  ['25', 'Gus Dean', 'Nitro Motorsports', 'Toyota', 'Shane Wilson'],
  ['26', 'Ron Vandermeir Jr.', 'Vanco Racing', 'Toyota', '—'],
  ['27', 'Tim Richmond', 'Tim Richmond Racing', 'Toyota', 'Adam Murphy'],
  ['28', 'Jack Wood', 'Pinnacle Racing Group', 'Chevrolet', 'Steven Dawson'],
  ['30', 'Garrett Mitchell', 'Rette Jones Racing', 'Ford', 'Mark Rette'],
  ['32', 'Charles Weslowski Jr.', 'Weslowski Racing', 'Chevrolet', 'Tim Silva'],
  ['34', 'Bryce Applegate', 'Mullins Racing', 'Chevrolet', 'Tony Furr'],
  ['36', 'Ryan Huff', 'Ryan Huff Motorsports', 'Ford', 'James Huff'],
  ['40', 'Andrew Patterson', 'Andrew Patterson Racing', 'Chevrolet', 'Patrick Torbett'],
  ['41', 'Robbie Kennealy', "Jan's Towing Racing", 'Ford', 'Tim Monroe'],
  ['48', 'Brad Smith', 'Brad Smith Motorsports', 'Ford', 'Terry Strange'],
  ['52', 'Robert Martin', 'Martin Racing', 'Toyota', 'Jeff Spraker'],
  ['55', 'Isabella Robusto', 'Nitro Motorsports', 'Toyota', 'Glenn Parker'],
  ['57', 'Hunter Deshautelle', 'Brother-In-Law Racing', 'Chevrolet', 'Todd Cooper'],
  ['62', 'Steve Lewis Jr.', 'Steve Lewis Racing', 'Chevrolet', 'Steve Lewis Sr'],
  ['66', 'Derek White', 'MBM Motorsports', 'Ford', 'Jeremy Petty'],
  ['68', 'Alli Owens', 'Kimmel Racing', 'Ford', 'Will Kimmel'],
  ['69', 'Nolan Wilson', 'Kimmel Racing', 'Chevrolet', 'Bill Kimmel'],
  ['70', 'Thomas Annunziata', 'Nitro Motorsports', 'Toyota', 'Shannon Rursch'],
  ['71', 'Andy Jankowiak', 'KLAS Motorsports', 'Chevrolet', 'Mike Dayton'],
  ['75', 'Bryan Dauzat', 'Brother-In-Law Racing', 'Chevrolet', 'Bob Rahilly'],
  ['76', 'Kole Raz', 'Rette Jones Racing', 'Ford', 'Greg Zipadelli'],
  ['77', 'Taylor Reimer', 'Pinnacle Racing Group', 'Chevrolet', 'Kevin Reed Jr'],
  ['86', 'Logan Misuraca', 'City Garage Motorsports', 'Ford', 'Ryan Bell'],
  ['88', 'A. J. Moyer', 'Moyer–Petroniro Racing', 'Chevrolet', 'Kevin Ingram'],
  ['89', 'Bobby Dale Earnhardt', 'Rise Racing', 'Chevrolet', 'Matthew Wright'],
  ['90', 'Wesley Slimp', 'Nitro Motorsports', 'Toyota', 'Jeff McClure'],
  ['91', 'Ryan Vargas', 'Maples Motorsports', 'Ford', 'Kyle Totman'],
  ['93', 'Caleb Costner', 'Costner Motorsports', 'Chevrolet', '—'],
  ['97', 'Jason Kitzmiller', 'CR7 Motorsports', 'Chevrolet', 'Frank Kimmel'],
  ['98', 'Dale Shearer', 'Shearer Speed Racing', 'Toyota', 'Vincenzo Valentin'],
  ['99', 'Michael Maples', 'Maples Motorsports', 'Chevrolet', 'Chris Vanscoy'],
];

const path = 'data/events/ARCA_2026_1.json';
const data = JSON.parse(fs.readFileSync(path, 'utf8'));
data.entry_list = entryList.map(([number, driver, team, manufacturer, crew_chief]) => ({
  number,
  driver,
  team,
  manufacturer,
  crew_chief: crew_chief || '',
}));
fs.writeFileSync(path, JSON.stringify(data, null, 2), 'utf8');
console.log('Updated ARCA_2026_1 entry_list:', data.entry_list.length, 'entries');
